/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i3 from './auth.component';
export declare const RenderType_FormioAuthComponent: i0.RendererType2;
export declare function View_FormioAuthComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_FormioAuthComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const FormioAuthComponentNgFactory: i0.ComponentFactory<i3.FormioAuthComponent>;
