/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './delete.component';
export declare const RenderType_FormioResourceDeleteComponent: i0.RendererType2;
export declare function View_FormioResourceDeleteComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_FormioResourceDeleteComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const FormioResourceDeleteComponentNgFactory: i0.ComponentFactory<i1.FormioResourceDeleteComponent>;
