/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i6 from './view.component';
export declare const RenderType_FormioResourceViewComponent: i0.RendererType2;
export declare function View_FormioResourceViewComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_FormioResourceViewComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const FormioResourceViewComponentNgFactory: i0.ComponentFactory<i6.FormioResourceViewComponent>;
